### ISSUE TITLE
[buyer] Create buyer model

### ISSUE THREAD

**Issue by aeciovc** [aeciovc/sda_django_myquote#1]
- Define a django model
name, email, id_code, phonenumber, dt_entrance

**Comment by astDeniss** [comment]
IN PROGRESS

**Comment by astDeniss** [comment]
@aeciovc cannot make a push request:

`
ERROR: Permission to aeciovc/sda_django_myquote.git denied to astDeniss.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by aeciovc** [comment]
@astDeniss  Done.

**Comment by astDeniss** [comment]
DONE.
