### ISSUE TITLE
[products] Create product model

### ISSUE THREAD

**Issue by aeciovc** [aeciovc/sda_django_myquote#4]
-Define a django model
name, description, brand, image, category (foreign_key) status (PUBLISHED, NOT_PUBLISHED)

**Comment by paulo-zacarias** [comment]
Hi,

I have a question.
When you mention that the status field should have value of either PUBLISHED or NOT_PUBLISHED, do you mean we should create a custom Field type (as described [here](https://docs.djangoproject.com/en/3.0/howto/custom-model-fields/)) or is it enough to use a Boolean type?

**Comment by aeciovc** [comment]
Hi,

I would say that a field as `models.CharField` having `choices` would be the best choice.
